Family-friend-invitation
aldab2/family_space pull request #18
Opened 2024-01-27 18:16 UTC by saudalibrahim

This pull is for friend handeler

2024-01-28 14:11 UTC, aabarnawi requested changes
Plz review my comments and let me know if you need to discuss anything

2024-01-28 14:11 UTC, aabarnawi commented on backend/DTOs/FamilyDTOs.js
> +      this.friendRequests = family.friendRequests
Did you forget to remove this ? 
Or you decided to put it back

2024-01-28 14:11 UTC, aabarnawi commented on backend/models/friendRequestModel.js
> +const friendRequestSchema = mongoose.Schema({
I suggest changing it to 
instead of sender first Name to sender which takes a user objectID 
and hence we can remove the  senderFirstName since it included in the user object

since the senderFamilyId is already there we dont need senderSpaceName since it included in the family 


Rename senderfamilyId to senderFamily
and recipentFamilyId to RecipentFamily

2024-01-28 14:11 UTC, aabarnawi commented on backend/controllers/friendController.js
> +      res.status(400).send("You can't add yourself as a friend.")
Please use our generic error middleware
see other error example for guidance , simply set the status and throw the error

2024-01-28 14:11 UTC, aabarnawi commented on backend/controllers/friendController.js
> +      res.status(400).send("This Family already a friend.")
Geniric err midleware

2024-01-28 14:11 UTC, aabarnawi commented on backend/controllers/friendController.js
> +    const newFriendRequest = new FriendReqest({
Apply suggestions in friendrequest model file and change this file accordingly

2024-01-28 14:11 UTC, aabarnawi commented on backend/controllers/friendController.js
> +      res.status(500).send("Error when trying to create friend request.")
err midleware + I suggest just throwing the error object inside 
like throw new Error(error)
and the middleware will handle it. if it doesnt we make it handle it later

2024-01-28 14:11 UTC, aabarnawi commented on backend/controllers/friendController.js
> +    await FriendReqest.findOneAndDelete({ _id: id })
I can delete friend request where I am neither a sender nor recipent 
plz fix

2024-01-28 14:11 UTC, aabarnawi commented on backend/controllers/friendController.js
> +    res.status(404).end()
generic err mdlware

2024-01-28 14:11 UTC, aabarnawi commented on backend/controllers/friendController.js
> +    const friendRequest = await FriendReqest.findOne({ _id: id });
can fetch to accept a friend request where user is not a recipent 
I know you are checking for recipent below but its more efficent to add the recipent ID in this query and remove the check below

2024-01-28 14:11 UTC, aabarnawi commented on backend/controllers/friendController.js
> +    if (!recipientFamilyId.equals(friendRequest.recipientFamilyId)) {
generic err midlware + 
could be removed if checked earlier

2024-01-28 14:11 UTC, aabarnawi commented on backend/controllers/friendController.js
> +      return res.status(400).send("The friend request has already been accepted.");
err mdlware

2024-01-28 14:11 UTC, aabarnawi commented on backend/controllers/friendController.js
> +    session.startTransaction();
first time to see this but if it is what I think it is, then its a great Idea, we might need to implement it in several other controllers

2024-01-28 14:11 UTC, aabarnawi commented on backend/controllers/friendController.js
> +      res.status(500).json({ message: "Failed to accept friend request." });
err mdlware

2024-01-28 14:11 UTC, aabarnawi commented on backend/controllers/friendController.js
> +    res.status(500).json({ message: "An error occurred." });
err mdlware

2024-01-28 14:11 UTC, aabarnawi commented on backend/controllers/friendController.js
> +    const friendRequest = await FriendReqest.findOne({ _id: id });
same comments mentioned above applies here

2024-01-28 14:11 UTC, aabarnawi commented on backend/controllers/friendController.js
> +    if (!recipientFamilyId.equals(friendRequest.recipientFamilyId)) {
could be removed + err mdlware

2024-01-28 14:11 UTC, aabarnawi commented on backend/controllers/friendController.js
> +      return res.status(404).send("Friend request not found.");
err mdlware

2024-01-28 14:11 UTC, aabarnawi commented on backend/controllers/friendController.js
> +  } catch (error) {
err mdlware

2024-01-28 14:11 UTC, aabarnawi commented on backend/controllers/friendController.js
> +
Why not using sessions here also ?

2024-01-28 14:11 UTC, aabarnawi commented on backend/controllers/friendController.js
> +    res.send("No errors")
should not return like this , 
should return the removed family object

2024-01-28 14:11 UTC, aabarnawi commented on backend/middleware/authMidleware.js
> +        res.status(401).send("Not authorized, Not a parent")
err mdlware

2024-01-28 14:11 UTC, aabarnawi commented on backend/middleware/authMidleware.js
> +        res.status(401).send("Not authorized, Not a parent")
I think returning forbidden is more accurate than not authorized 401

2024-01-28 14:11 UTC, aabarnawi commented on backend/middleware/authMidleware.js
> +        res.status(401).send("Not authorized, Not an adult")
same here

2024-01-29 14:14 UTC, saudalibrahim commented on backend/DTOs/FamilyDTOs.js
> +      this.friendRequests = family.friendRequests
yes romoved now

2024-02-03 19:23 UTC, saudalibrahim commented on backend/controllers/friendController.js
> +      res.status(400).send("You can't add yourself as a friend.")
noted

2024-02-03 19:24 UTC, saudalibrahim commented on backend/controllers/friendController.js
> +      res.status(400).send("This Family already a friend.")
updated

2024-02-03 19:31 UTC, saudalibrahim commented on backend/controllers/friendController.js
> +    res.status(404).end()
updated

2024-02-03 19:32 UTC, saudalibrahim commented on backend/controllers/friendController.js
> +      return res.status(400).send("The friend request has already been accepted.");
updated

2024-02-03 19:34 UTC, saudalibrahim commented on backend/controllers/friendController.js
> +      res.status(500).json({ message: "Failed to accept friend request." });
updated

2024-02-03 19:35 UTC, saudalibrahim commented on backend/controllers/friendController.js
> +    res.status(500).json({ message: "An error occurred." });
updated

2024-02-03 19:37 UTC, saudalibrahim commented on backend/controllers/friendController.js
> +  } catch (error) {
updated

2024-02-05 16:03 UTC, saudalibrahim commented on backend/models/friendRequestModel.js
> +const friendRequestSchema = mongoose.Schema({
updated

2024-02-05 16:06 UTC, saudalibrahim commented on backend/controllers/friendController.js
> +    const newFriendRequest = new FriendReqest({
updated

2024-02-05 16:11 UTC, saudalibrahim commented on backend/controllers/friendController.js
> +    const friendRequest = await FriendReqest.findOne({ _id: id });
updated

2024-02-05 16:16 UTC, saudalibrahim commented on backend/controllers/friendController.js
> +    if (!recipientFamilyId.equals(friendRequest.recipientFamilyId)) {
removed

2024-02-05 16:16 UTC, saudalibrahim commented on backend/controllers/friendController.js
> +      return res.status(404).send("Friend request not found.");
updated

2024-02-05 16:16 UTC, saudalibrahim commented on backend/controllers/friendController.js
> +    const friendRequest = await FriendReqest.findOne({ _id: id });
updated

2024-02-05 16:56 UTC, saudalibrahim commented on backend/controllers/friendController.js
> +
Causes alot of errors so i removed it

2024-02-05 16:56 UTC, saudalibrahim commented on backend/controllers/friendController.js
> +    res.send("No errors")
updated please check

2024-02-06 18:27 UTC, saudalibrahim commented on backend/controllers/friendController.js
> +    session.startTransaction();
removed alot of errors

2024-02-06 18:29 UTC, saudalibrahim commented on backend/controllers/friendController.js
> +    await FriendReqest.findOneAndDelete({ _id: id })
now fixed

2024-02-06 18:30 UTC, saudalibrahim commented on backend/controllers/friendController.js
> +      res.status(500).send("Error when trying to create friend request.")
ficed

2024-02-06 18:57 UTC, merged